name: Manual Movie Recommendations Trigger

on: workflow_dispatch

jobs:
  build:
    environment: ENV_SECRET
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Running Scripts
        env:
          TMDB_SECRET: ${{ secrets.ENV_SECRET.TMDB_SECRET }}
          TRAKT_SECRET: ${{ secrets.ENV_SECRET.TRAKT_SECRET }} 
          UN_SECRET: ${{ secrets.ENV_SECRET.UN_SECRET }} 
        run: |
          pip install -r requirements.txt
          python script.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated Movies"
          git push
